import { NextConfig } from "next";

const baseConfig: NextConfig = {
  reactStrictMode: true,
  productionBrowserSourceMaps: false,
  poweredByHeader: false,
  // Baked into the bundle at build time and read back by lib/version.ts for
  // GET /api/version. Vercel always provides VERCEL_GIT_COMMIT_SHA to the
  // BUILD; whether it is also exposed to functions at runtime is a project
  // setting, so the build-time copy is the one that always exists. Empty
  // string (not undefined) so a local build resolves to `unknown` rather
  // than leaking a stale value from a developer's shell.
  env: {
    APP_BUILD_GIT_SHA: process.env.VERCEL_GIT_COMMIT_SHA ?? "",
    APP_BUILD_GIT_REF: process.env.VERCEL_GIT_COMMIT_REF ?? "",
    APP_BUILD_VERCEL_ENV: process.env.VERCEL_ENV ?? "",
    APP_BUILD_TIME: new Date().toISOString(),
  },
  // Tree-shake barrel imports (icons/animation/charts) at build time — shrinks
  // the client bundle without per-component dynamic imports, which trip the
  // Turbopack SSG bug with framer-motion (see CLAUDE.md).
  experimental: {
    optimizePackageImports: ["lucide-react", "framer-motion", "recharts"],
  },
  images: {
    // No `remotePatterns`. It used to be `hostname: "**"`, which turns
    // /_next/image into an OPEN IMAGE PROXY: anyone can pass any URL and have
    // this domain fetch, optimise, cache and serve it — someone else's
    // bandwidth bill, arbitrary bytes served from our origin, and a Vercel
    // image-transformation quota anybody can burn.
    //
    // Nothing here needs it: every image is local (`/Images/**`,
    // `/projects/**`) or generated by our own `/api/og`. Verified across the
    // components, `constants/projects.ts`, the blog frontmatter and the
    // generated manifest — zero remote image sources.
    //
    // If a remote source is ever added, list that ONE host here rather than
    // restoring the wildcard.
    // Local images are blocked from carrying a query string unless allow-listed,
    // and both the per-post and the per-project branded covers are rendered by
    // `/api/og?title=…`. Without the first entry the build fails at prerender
    // with "using a query string which is not configured in localPatterns".
    // The second entry keeps every other local path (/Images/**, /projects/**)
    // working — listing `localPatterns` at all opts everything into the allow-list.
    localPatterns: [{ pathname: "/api/og", search: "**" }, { pathname: "/**" }],
    formats: ["image/avif", "image/webp"],
  },
  typescript: {
    ignoreBuildErrors: false,
  },
  // Guessable URLs that used to 404. Each is a URL a recruiter types by hand
  // or an old link elsewhere still points at. `/blog` → `/blogs` and
  // `/hire(-me)` → `/services` are page-level permanentRedirect()s beside
  // their routes; these three have no page of their own, so they live here.
  // e2e/routes.ts REDIRECT_ROUTES asserts every one of them.
  async redirects() {
    return [
      { source: "/projects", destination: "/portfolio", permanent: true },
      { source: "/work", destination: "/portfolio", permanent: true },
      {
        source: "/resume",
        destination: "/Shailesh_Chaudhari_Resume.pdf",
        permanent: true,
      },
    ];
  },
};

// Bundle analysis findings (run: npm run analyze)
// Top offenders (client bundle, 2026-04-17):
//   recharts + lodash  394 kB  — already lazy-loaded (ssr:false dynamic import)
//   lucide-react       359 kB  — named imports only, tree-shaken as well as possible
//   Next.js internals  217 kB  — framework overhead, not optimizable
//   yup (removed)      195 kB  — eliminated; replaced with react-hook-form built-in rules
//
// Optionally wrap with bundle analyzer when ANALYZE=true
let nextConfig: NextConfig = baseConfig;
try {
  if (process.env.ANALYZE === "true") {
    // eslint-disable-next-line @typescript-eslint/no-var-requires, @typescript-eslint/no-require-imports
    const withBundleAnalyzer = require("@next/bundle-analyzer")({
      enabled: true,
    });
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    nextConfig = withBundleAnalyzer(baseConfig as any) as NextConfig;
  }
} catch {
  // If analyzer isn't installed, fall back to base config
  nextConfig = baseConfig;
}

const finalConfig = nextConfig;
export default finalConfig;
