import { MetadataRoute } from "next";
import { blogPosts } from "@/lib/blog-data";
import { projects } from "@/constants/projects";
import { SITE_URL } from "@/lib/blog-constants";
import routeModified from "@/lib/route-modified.json";

/**
 * Real last-change date for a route, from git history (lib/route-modified.json,
 * regenerated by scripts/generate-route-dates.mjs on prebuild).
 *
 * This used to be `new Date()` on every static route, so each deploy claimed
 * every page had changed that day. Against git that was false by four months
 * for /about and /contact. Google discounts a lastModified that never disagrees
 * with the crawl date, which meant the pages that HAD genuinely changed got no
 * benefit from the field either.
 *
 * The fallback is the epoch-ish sentinel rather than now, on purpose: an
 * unknown route should understate its freshness, never overstate it.
 */
const modified = (route: string): Date => {
  const d = (routeModified as Record<string, string | null>)[route];
  return d ? new Date(`${d}T00:00:00Z`) : new Date("2026-01-01T00:00:00Z");
};

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  // Static routes — image annotation lifts these into Google Discover
  // and Image search. The OG image is a per-page render so it's distinct
  // for each route.
  const ogFor = (path: string) =>
    `${SITE_URL}/api/og?title=${encodeURIComponent("Shailesh Chaudhari")}&type=page&description=${encodeURIComponent(path)}`;
  const staticRoutes: MetadataRoute.Sitemap = [
    {
      url: `${SITE_URL}/`,
      lastModified: modified("/"),
      changeFrequency: "weekly",
      priority: 1,
      images: [`${SITE_URL}/Images/shailesh.webp`],
    },
    {
      url: `${SITE_URL}/blogs`,
      lastModified: modified("/blogs"),
      changeFrequency: "weekly",
      priority: 0.9,
      images: [ogFor("/blogs")],
    },
    {
      url: `${SITE_URL}/about`,
      lastModified: modified("/about"),
      changeFrequency: "monthly",
      priority: 0.9,
      images: [`${SITE_URL}/Images/shailesh.webp`],
    },
    {
      url: `${SITE_URL}/contact`,
      lastModified: modified("/contact"),
      changeFrequency: "yearly",
      priority: 0.6,
      images: [ogFor("/contact")],
    },
    {
      url: `${SITE_URL}/portfolio`,
      lastModified: modified("/portfolio"),
      changeFrequency: "weekly",
      priority: 0.95,
      images: [ogFor("/portfolio")],
    },
    {
      url: `${SITE_URL}/services`,
      lastModified: modified("/services"),
      changeFrequency: "monthly",
      priority: 0.9,
      images: [ogFor("/services")],
    },
    {
      url: `${SITE_URL}/engineering`,
      lastModified: modified("/engineering"),
      changeFrequency: "monthly",
      priority: 0.9,
      images: [ogFor("/engineering")],
    },
    {
      url: `${SITE_URL}/statistics`,
      lastModified: modified("/statistics"),
      changeFrequency: "weekly",
      priority: 0.7,
      images: [ogFor("/statistics")],
    },
    {
      url: `${SITE_URL}/now`,
      lastModified: modified("/now"),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [ogFor("/now")],
    },
  ];

  // Dynamic blog post routes — `images` is a Google Discover ranking signal
  // and surfaces hero images directly in the search index.
  const dynamicBlogRoutes: MetadataRoute.Sitemap = blogPosts.map((post) => ({
    url: `${SITE_URL}/blog/${post.slug}`,
    lastModified: post.lastModified
      ? new Date(post.lastModified)
      : new Date(post.date),
    changeFrequency: "monthly",
    priority: post.featured ? 0.8 : 0.6,
    images: post.image ? [`${SITE_URL}${post.image}`] : undefined,
  }));

  // Dynamic portfolio project routes — same image-annotation treatment.
  const dynamicPortfolioRoutes: MetadataRoute.Sitemap = projects.map(
    (project) => ({
      url: `${SITE_URL}/portfolio/${project.id}`,
      // Every project page renders from constants/projects.ts, so they share
      // that file's real date rather than each inventing "now".
      lastModified: modified("__projects__"),
      changeFrequency: "monthly",
      priority: project.isShowcase ? 0.8 : 0.6,
      images: project.image ? [`${SITE_URL}${project.image}`] : undefined,
    })
  );

  return [...staticRoutes, ...dynamicBlogRoutes, ...dynamicPortfolioRoutes];
}
