// Centralized blog data source — metadata only.
// Content lives in content/blog/<slug>.mdx (HTML body after frontmatter).
// To add a post: create the MDX file, add its slug to BLOG_SLUGS below.
// Generated by: node scripts/migrate-blog.mjs

import { readFileSync } from "node:fs";
import { join } from "node:path";
import matter from "gray-matter";

export interface BlogPost {
  slug: string;
  title: string;
  subtitle?: string;
  description: string;
  content: string;
  image: string;
  author: {
    name: string;
    avatar: string;
    bio: string;
    role: string;
    social: {
      twitter?: string;
      github?: string;
      linkedin?: string;
    };
  };
  date: string;
  readTime: string;
  tags: string[];
  featured?: boolean;
  seoKeywords: string[];
  lastModified?: string;
  /**
   * `archived: true` in frontmatter. The post still renders at /blog/<slug>
   * (its URL keeps returning 200 and stays in the sitemap) but it is excluded
   * from the blog index, the home page, the RSS feed and the tag lists, and
   * it renders with a "From the archive" note.
   *
   * Used for the 2024 batch: seventeen posts published 2024-09-28 to
   * 2024-10-09 that were written for search traffic, not to say anything.
   * Deleting them would break inbound links; leading with them would tell a
   * recruiter the wrong story about what the blog is for.
   */
  archived: boolean;
}

// Sourced from lib/profile.ts (single-source-of-truth for identity facts).
// Anything about name / role / bio / location lives there.
import { PROFILE } from "./profile";

export const BLOG_AUTHOR = {
  name: PROFILE.name.full,
  avatar: "/Images/shailesh.webp",
  bio: PROFILE.bio.short,
  role: PROFILE.role.positioning,
  social: {
    twitter: "https://twitter.com/ShaileshWork",
    github: "https://github.com/Shailesh93602",
    linkedin: "https://linkedin.com/in/shaileshbhaichaudhari",
  },
};

// Slugs in publication order — add new slugs here when adding posts.
export const BLOG_SLUGS: string[] = [
  "a-passing-test-only-proves-the-test-passes",
  "khatago-webhook-deduplication-receipt-pipeline",
  "mutation-score-was-100-percent-because-tests-were-broken",
  "introduction-to-nestjs-for-backend-development",
  "how-to-use-nextjs-for-seo-friendly-web-apps",
  "step-by-step-guide-mern-stack-application",
  "solving-700-dsa-problems",
  "first-year-software-engineer-lessons",
  "internship-to-engineer-journey",
  "how-team-collaboration-made-me-better-developer",
  "building-portfolio-website-nextjs-tailwindcss",
  "challenges-junior-developer-overcame",
  "importance-code-reviews-learning-senior-mrs",
  "transitioning-learning-to-real-world-applications",
  "setting-up-authentication-supabase-nextjs",
  "integrating-stripe-payments-nodejs-nextjs",
  "implementing-oauth-web-application",
  "tailwindcss-nextjs-faster-ui-development",
  "getting-started-shadcn-ui-modern-react-applications",
  "best-practices-api-development-express-nestjs",
  "building-inventory-engine-never-oversells-concurrency",
  "production-rag-that-says-i-dont-know",
  "idempotency-keys-retry-safe-payment-apis",
  // DRAFTS — uncomment each slug after filling in [FILL IN:] placeholders in content/blog/<slug>.mdx
  // "eduscale-redis-distributed-locks-real-time",
  // "postgres-rbac-eduscale-permissions",
  // "khatago-webhook-deduplication-receipt-pipeline",
];

// Posts that never had a real cover historically all point at this shared
// placeholder. Treat it (and an empty value) as "no cover" so we render a
// branded, per-post OG image instead of the same generic screenshot 24×.
const PLACEHOLDER_COVER = "/Images/portfolio1.png";

/** Branded per-post cover via the OG image generator (title + gradient). */
function generatedCover(title: string, description: string): string {
  const params = new URLSearchParams({ title, type: "blog" });
  if (description) params.set("description", description);
  return `/api/og?${params.toString()}`;
}

function loadPost(slug: string): BlogPost | null {
  try {
    const filePath = join(process.cwd(), "content", "blog", `${slug}.mdx`);
    const raw = readFileSync(filePath, "utf8");
    const { data, content } = matter(raw);
    const title = data.title ?? "";
    const description = data.description ?? "";
    const rawImage = data.image ?? "";
    const image =
      !rawImage || rawImage === PLACEHOLDER_COVER
        ? generatedCover(title || slug, description)
        : rawImage;
    return {
      slug,
      title,
      subtitle: data.subtitle,
      description,
      content,
      image,
      author: BLOG_AUTHOR,
      date: data.date ?? "",
      readTime: data.readTime ?? "",
      tags: data.tags ?? [],
      featured: data.featured ?? false,
      seoKeywords: data.seoKeywords ?? [],
      lastModified: data.lastModified,
      archived: data.archived === true,
    };
  } catch {
    return null;
  }
}

// Loaded once at module init — only runs server-side (fs usage is intentional).
/** Every post that renders — used by the sitemap and static params. */
export const blogPosts: BlogPost[] = BLOG_SLUGS.map(loadPost).filter(
  Boolean
) as BlogPost[];

/** Every post the site SURFACES — listing, home, feed, tags, related posts. */
export const publishedPosts: BlogPost[] = blogPosts.filter((p) => !p.archived);

export const getPostBySlug = (slug: string): BlogPost | undefined =>
  blogPosts.find((p) => p.slug === slug);

export const getRelatedPosts = (slug: string, limit = 3): BlogPost[] => {
  const post = getPostBySlug(slug);
  if (!post) return [];
  return publishedPosts
    .filter((p) => p.slug !== slug && p.tags.some((t) => post.tags.includes(t)))
    .slice(0, limit);
};

export const getFeaturedPosts = (): BlogPost[] =>
  publishedPosts.filter((p) => p.featured);

export const getAllTags = (): string[] => {
  const tags = new Set<string>();
  publishedPosts.forEach((p) => p.tags.forEach((t) => tags.add(t)));
  return Array.from(tags).sort((a, b) => a.localeCompare(b));
};

export const getPostsByTag = (tag: string): BlogPost[] =>
  publishedPosts.filter((p) => p.tags.includes(tag));
