// Centralized blog data source — metadata only.
// Content lives in content/blog/<slug>.mdx (HTML body after frontmatter).
// To add a post: create the MDX file, add its slug to BLOG_SLUGS below.
// Generated by: node scripts/migrate-blog.mjs

import { readFileSync } from "node:fs";
import { join } from "node:path";
import matter from "gray-matter";

export interface BlogPost {
  slug: string;
  title: string;
  subtitle?: string;
  description: string;
  content: string;
  image: string;
  author: {
    name: string;
    avatar: string;
    bio: string;
    role: string;
    social: {
      twitter?: string;
      github?: string;
      linkedin?: string;
    };
  };
  date: string;
  readTime: string;
  tags: string[];
  featured?: boolean;
  seoKeywords: string[];
  lastModified?: string;
}

// Sourced from lib/profile.ts (single-source-of-truth for identity facts).
// Anything about name / role / bio / location lives there.
import { PROFILE } from "./profile";

export const BLOG_AUTHOR = {
  name: PROFILE.name.full,
  avatar: "/Images/shailesh.webp",
  bio: PROFILE.bio.short,
  role: PROFILE.role.positioning,
  social: {
    twitter: "https://twitter.com/ShaileshWork",
    github: "https://github.com/Shailesh93602",
    linkedin: "https://linkedin.com/in/shaileshbhaichaudhari",
  },
};

// Slugs in publication order — add new slugs here when adding posts.
export const BLOG_SLUGS: string[] = [
  "introduction-to-nestjs-for-backend-development",
  "how-to-use-nextjs-for-seo-friendly-web-apps",
  "step-by-step-guide-mern-stack-application",
  "solving-700-dsa-problems",
  "first-year-software-engineer-lessons",
  "internship-to-engineer-journey",
  "how-team-collaboration-made-me-better-developer",
  "building-portfolio-website-nextjs-tailwindcss",
  "challenges-junior-developer-overcame",
  "importance-code-reviews-learning-senior-mrs",
  "transitioning-learning-to-real-world-applications",
  "setting-up-authentication-supabase-nextjs",
  "integrating-stripe-payments-nodejs-nextjs",
  "implementing-oauth-web-application",
  "tailwindcss-nextjs-faster-ui-development",
  "getting-started-shadcn-ui-modern-react-applications",
  "best-practices-api-development-express-nestjs",
  // DRAFTS — uncomment each slug after filling in [FILL IN:] placeholders in content/blog/<slug>.mdx
  // "eduscale-redis-distributed-locks-real-time",
  // "postgres-rbac-eduscale-permissions",
  // "khatago-webhook-deduplication-receipt-pipeline",
];

function loadPost(slug: string): BlogPost | null {
  try {
    const filePath = join(process.cwd(), "content", "blog", `${slug}.mdx`);
    const raw = readFileSync(filePath, "utf8");
    const { data, content } = matter(raw);
    return {
      slug,
      title: data.title ?? "",
      subtitle: data.subtitle,
      description: data.description ?? "",
      content,
      image: data.image ?? "",
      author: BLOG_AUTHOR,
      date: data.date ?? "",
      readTime: data.readTime ?? "",
      tags: data.tags ?? [],
      featured: data.featured ?? false,
      seoKeywords: data.seoKeywords ?? [],
      lastModified: data.lastModified,
    };
  } catch {
    return null;
  }
}

// Loaded once at module init — only runs server-side (fs usage is intentional).
export const blogPosts: BlogPost[] = BLOG_SLUGS.map(loadPost).filter(
  Boolean
) as BlogPost[];

export const getPostBySlug = (slug: string): BlogPost | undefined =>
  blogPosts.find((p) => p.slug === slug);

export const getRelatedPosts = (slug: string, limit = 3): BlogPost[] => {
  const post = getPostBySlug(slug);
  if (!post) return [];
  return blogPosts
    .filter((p) => p.slug !== slug && p.tags.some((t) => post.tags.includes(t)))
    .slice(0, limit);
};

export const getFeaturedPosts = (): BlogPost[] =>
  blogPosts.filter((p) => p.featured);

export const getAllTags = (): string[] => {
  const tags = new Set<string>();
  blogPosts.forEach((p) => p.tags.forEach((t) => tags.add(t)));
  return Array.from(tags).sort((a, b) => a.localeCompare(b));
};

export const getPostsByTag = (tag: string): BlogPost[] =>
  blogPosts.filter((p) => p.tags.includes(tag));
