// Centralized blog data source — metadata only.
// Content lives in content/blog/<slug>.mdx (HTML body after frontmatter).
// To add a post: create the MDX file, add its slug to BLOG_SLUGS below.
// Generated by: node scripts/migrate-blog.mjs

import { readFileSync } from "fs";
import { join } from "path";
import matter from "gray-matter";

export interface BlogPost {
  slug: string;
  title: string;
  subtitle?: string;
  description: string;
  content: string;
  image: string;
  author: {
    name: string;
    avatar: string;
    bio: string;
    role: string;
    social: {
      twitter?: string;
      github?: string;
      linkedin?: string;
    };
  };
  date: string;
  readTime: string;
  tags: string[];
  featured?: boolean;
  seoKeywords: string[];
  lastModified?: string;
}

export const BLOG_AUTHOR = {
  name: "Shailesh Chaudhari",
  avatar: "/Images/shailesh.webp",
  bio: "Software Engineer passionate about creating efficient, scalable, and user-friendly web applications. Expert in full-stack development with modern technologies and strong problem-solving skills.",
  role: "Full-Stack Developer & Problem Solver",
  social: {
    twitter: "https://twitter.com/shaileshwork",
    github: "https://github.com/Shailesh93602",
    linkedin: "https://linkedin.com/in/shaileshbhaichaudhari",
  },
};

// Slugs in publication order — add new slugs here when adding posts.
export const BLOG_SLUGS: string[] = [
  "introduction-to-nestjs-for-backend-development",
  "how-to-use-nextjs-for-seo-friendly-web-apps",
  "step-by-step-guide-mern-stack-application",
  "solving-700-dsa-problems",
  "first-year-software-engineer-lessons",
  "internship-to-engineer-journey",
  "how-team-collaboration-made-me-better-developer",
  "building-portfolio-website-nextjs-tailwindcss",
  "challenges-junior-developer-overcame",
  "importance-code-reviews-learning-senior-mrs",
  "transitioning-learning-to-real-world-applications",
  "setting-up-authentication-supabase-nextjs",
  "integrating-stripe-payments-nodejs-nextjs",
  "implementing-oauth-web-application",
  "tailwindcss-nextjs-faster-ui-development",
  "getting-started-shadcn-ui-modern-react-applications",
  "best-practices-api-development-express-nestjs",
];

function loadPost(slug: string): BlogPost | null {
  try {
    const filePath = join(process.cwd(), "content", "blog", `${slug}.mdx`);
    const raw = readFileSync(filePath, "utf8");
    const { data, content } = matter(raw);
    return {
      slug,
      title: data.title ?? "",
      subtitle: data.subtitle,
      description: data.description ?? "",
      content,
      image: data.image ?? "",
      author: BLOG_AUTHOR,
      date: data.date ?? "",
      readTime: data.readTime ?? "",
      tags: data.tags ?? [],
      featured: data.featured ?? false,
      seoKeywords: data.seoKeywords ?? [],
      lastModified: data.lastModified,
    };
  } catch {
    return null;
  }
}

let _cache: BlogPost[] | null = null;
function getAllPosts(): BlogPost[] {
  if (!_cache) {
    _cache = BLOG_SLUGS.map(loadPost).filter(Boolean) as BlogPost[];
  }
  return _cache;
}

export const blogPosts: BlogPost[] = new Proxy([] as BlogPost[], {
  get(_, prop) {
    return (getAllPosts() as unknown as Record<string | symbol, unknown>)[prop];
  },
});

export const getPostBySlug = (slug: string): BlogPost | undefined =>
  getAllPosts().find((p) => p.slug === slug);

export const getRelatedPosts = (slug: string, limit = 3): BlogPost[] => {
  const post = getPostBySlug(slug);
  if (!post) return [];
  return getAllPosts()
    .filter((p) => p.slug !== slug && p.tags.some((t) => post.tags.includes(t)))
    .slice(0, limit);
};

export const getFeaturedPosts = (): BlogPost[] =>
  getAllPosts().filter((p) => p.featured);

export const getAllTags = (): string[] => {
  const tags = new Set<string>();
  getAllPosts().forEach((p) => p.tags.forEach((t) => tags.add(t)));
  return Array.from(tags).sort((a, b) => a.localeCompare(b));
};

export const getPostsByTag = (tag: string): BlogPost[] =>
  getAllPosts().filter((p) => p.tags.includes(tag));
